language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t abc/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true abc/react-test-app npm run test

after_success:
  - docker build -t docker-frontend ./frontend
  - docker tag docker-frontend hkpark/docker-frontend
  - docker build -t docker-backend ./backend
  - docker tag docker-backend hkpark/docker-backend
  - docker build -t docker-nginx ./nginx
  - docker tag docker-nginx hkpark/docker-nginx

  - docker login -u "$DOCKER_HUB_ID" -p "$DOCKER_HUB_PASSWORD"

  - docker push hkpark/docker-frontend
  - docker push hkpark/docker-backend
  - docker push hkpark/docker-nginx
   